# Generated by Django 5.2.3 on 2026-02-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_produto_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckboxSell',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
